services:

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    container_name: spring-boot-task-management-backend-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      # Maven cache to speed up builds
      - maven-cache:/root/.m2
    environment:
      # Enable Spring DevTools
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: postgres-db-task-management
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  maven-cache: